#GitHub workflow - YAML GitHub workflow(github-workflow.json)
name: ETL pipeline

on:
  push:
    branches:
        - main
      
jobs:
  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: action/checkout@v7
      - name: run Python code
        run: python extract.py
      

  transform-job:
    needs: extract-job
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: action/checkout@v7
     - name: run Python code
       run: python transform.py

  load-job:
    needs: transform-job
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: action/checkout@v7
     - name: run Python code
       run: python load.py
  



